Fix cell complex methods
pyt-team/TopoNetX pull request #194
Opened 2023-07-11 21:04 UTC by mhajij

the following methods were added

1- get_linegraph : the simplest graph that can be attached to a cell complex
2- all_cell_to_node_codjacnecy_matrix 
3-node_to_all_cell_adjacnecy_matrix

based on the above the following methods were corrected

1- s_connected_components
2- s_component_subcomplexes
3- connected_components
4- connected_component_subcomplexes
5- node_diameters
6- cell_diameters
7- diameter
8- cell_diameter
9- distance
10- cell_distance

2023-07-12 06:57 UTC, ffl096 requested changes
Not sure if this was a bad merge or something, but this pull request removes many recent changes to `cell_complex.py`. Please fix :)

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        self.name = name
```suggestion
        super().__init__(name, **kwargs)
```
(No need to set `self.name` if passing the name to the superclass)

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def degree(self, node: Hashable, rank: int = 1) -> int:
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -        rank : int, default=1
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def cell_neighbors(self, cell, s: int = 1):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -        s : int, default=1
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def remove_node(self, node: Hashable) -> None:
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def add_node(self, node: Hashable, **attr) -> None:
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def _add_nodes_from(self, nodes: Iterable[Hashable]) -> None:
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def add_edge(self, u_of_edge: Hashable, v_of_edge: Hashable, **attr) -> None:
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def add_edges_from(self, ebunch_to_add: Iterable[tuple], **attr) -> None:
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -        check_skeleton: bool = False,
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -        check_skeleton: bool = False,
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def set_cell_data(self, cell, rank, attr_name: str, attr_value):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def get_cell_data(self, cell, rank, attr_name: str | None = None):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def remove_equivalent_cells(self) -> None:
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        index : boolean, optional, default False
```suggestion
        index : bool, default=False
```

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        index : boolean, optional, default False
```suggestion
        index : bool, default=False
```

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        index : boolean, optional, default False
```suggestion
        index : bool, default=False
```

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -        self, rank: int, signed: bool = True, weight: bool = False, index: bool = False
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    def is_connected(self, s: int = 1, cells: bool = False):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        s : int
```suggestion
        s : int, default=1
```

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        cells : bool, optional, default=True
```suggestion
        cells : bool, default=True
```

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        if isinstance(s, None):
Remove this check

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def s_connected_components(self, s=1, cells=True, return_singletons=False):
Please add the type hints back (for some reason GitHub shows the old line somewhat further above)

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        >>> # [{2, 3, 4, 5, 6, 7}]
```suggestion
        [{2, 3, 4, 5, 6, 7}]
```

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        >>> # [{2, 3, 4}, {5, 6, 7}]
```suggestion
        [{2, 3, 4}, {5, 6, 7}]
```

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> -    ):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def connected_components(self, cells=False, return_singletons=True):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def connected_component_subcomplexes(self, return_singletons=True):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +
Remove empty line

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def cell_diameters(self, s=1):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        diameter : int
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        cell_diameter : int
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def distance(self, source, target, s=1):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        s-walk distance : int
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def cell_distance(self, source, target, s=1):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +        >>> G.add_edge(1,2)
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def load_mesh(cls, file_path, process=False, force=None) -> "CellComplex":
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def __str__(self):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def __len__(self):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def __iter__(self):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def __contains__(self, item):
Please undo.

2023-07-12 06:57 UTC, ffl096 commented on toponetx/classes/cell_complex.py
> +    def _remove_equivalent_cells(self):
Please undo.

2023-07-12 19:59 UTC, mhajij commented
> Not sure if this was a bad merge or something, but this pull request removes many recent changes to `cell_complex.py`. Please fix :)

fixed now.

2023-07-19 00:31 UTC, USFCA-MSDS approved these changes

2023-07-19 00:32 UTC, USFCA-MSDS approved these changes

2023-07-19 00:34 UTC, merged