adding dirac operator
pyt-team/TopoNetX pull request #278
Opened 2023-10-12 06:06 UTC by IJabea

Adding dirac operator 

https://arxiv.org/abs/2301.10137

2023-10-12 14:18 UTC, ninamiolane requested changes
Missing tests. Every PR should come with its unit-tests.

2023-10-12 23:04 UTC, mhajij approved these changes

2023-10-12 23:05 UTC, mhajij approved these changes

2023-10-13 08:00 UTC, ffl096 requested changes
I don't like the test cases to be honest. While it satisfies code coverage, it really doesn't test that the result is correct. Can we please add an explicit (hand-calculated) result for a simple example and assert that the function returns exactly this matrix?

2023-10-13 14:29 UTC, ninamiolane requested changes
I agree with @ffl096 💯

2023-10-14 09:07 UTC, merged