Increasing test coverage for TopoNetX (5)
pyt-team/TopoNetX pull request #287
Opened 2023-10-17 22:45 UTC by gurug-dev

Draft PR, please do not merge.

2023-10-17 22:51 UTC, gurug-dev commented
Failing testcases are unrelated to changed code, unknown issue with TestMeshDatasets.

2023-10-18 00:16 UTC, gurug-dev commented on toponetx/classes/reportviews.py
>          return hyperedge_
Reordered the if-else block.

2023-10-18 00:16 UTC, gurug-dev commented on toponetx/classes/reportviews.py
> +                    if frozenset(e) in self.hyperedge_dict[i]:
same as above, reordered the if-else block.

2023-10-18 00:20 UTC, mhajij commented
@gurug-dev  all unit tests must pass

2023-10-18 00:22 UTC, gurug-dev commented
> @gurug-dev all unit tests must pass

FAILED test/datasets/test_mesh.py::TestMeshDatasets::test_shrec_16 - zipfile.BadZipFile: File is not a zip file
FAILED test/datasets/test_mesh.py::TestMeshDatasets::test_coseg - zipfile.BadZipFile: File is not a zip file

Hi Professor, failling test cases are unrelated to changed code.

2023-10-19 14:40 UTC, ninamiolane commented
@gurug-dev why are tests failing? How can we solve it? We can't merge a failing PR.

2023-10-19 14:45 UTC, ninamiolane requested changes
We can't merge a PR that fails the test: it will fail the whole repository. Need to fix the fails first.

2023-10-19 15:32 UTC, gurug-dev commented
> @gurug-dev why are tests failing? How can we solve it? We can't merge a failing PR.

@ninamiolane - i'm trying to figure it out, the test suite is passes locally, but the tests are failing in my forked branches (without the changes) on github as well. my best guess is some github actions related issue. will raise a PR if i'm able to solve it.

2023-10-19 21:29 UTC, gurug-dev commented
@ninamiolane @mhajij - the mesh datasets issue has been fixed, the test suite is now passing. For avoiding further issues, the mesh datasets need to be potentially moved to a server that is not github.

2023-10-19 21:30 UTC, mhajij approved these changes

2023-10-19 21:31 UTC, mhajij approved these changes

2023-10-19 21:31 UTC, mhajij approved these changes

2023-10-19 21:33 UTC, mhajij approved these changes

2023-10-19 21:35 UTC, merged