adding random cell complex generator
pyt-team/TopoNetX pull request #304
Opened 2023-11-02 16:39 UTC by mhajij

2023-11-02 21:03 UTC, ffl096 commented
We should come up with a better naming scheme. The function name is weird to me. In particular, "complex" is twice in the name, first as part of "cc" and as suffix at the end.

2023-11-07 19:28 UTC, devendragovil requested changes

2023-11-07 19:28 UTC, devendragovil commented on toponetx/generators/random_cell_complexes.py
> +def cc_np_complex(n: int, p: float, seed=None) -> CellComplex:
seed=None is invalid default condition as it will raise an exception, when the user doesn't provide a seed.

2023-11-07 19:28 UTC, devendragovil commented on test/generators/test_random_cell_complexes - Copy.py
> +        assert cc.shape[0] == 5
Ideally a test case for initialization without the second argument (seed) must be added.

2023-11-10 07:36 UTC, ffl096 requested changes
Please also update `docs/api/generators.rst` to generate documentation for the new module.

2023-11-10 07:36 UTC, ffl096 commented on test/generators/test_random_cell_complexes.py
> +class TestCcNpComplex:
Name is not correct.

2023-11-10 13:03 UTC, devendragovil reviewed
LGTM, I have checked the docstrings in particular for compliance with numpydoc.

2023-11-10 17:27 UTC, devendragovil approved these changes
LGTM. The docs file has also been updated.

2023-11-10 17:39 UTC, merged