Fixing some issues with docstrings and adding CI/CD step
pyt-team/TopoNetX pull request #318
Opened 2023-11-13 07:32 UTC by devendragovil

This PR does two things:

1. It fixes some docstrings issues with various modules in the library. 
2. It adds an explicit CI/CD step where now numpydoc will validate docstrings to make sure that they are in compliance, otherwise the CI/CD should fail. 

The second is in my opinion important because otherwise the docstrings are not compliant to numpy, and in many cases is not reliably parsed by Sphinx while generating docs. 

The Sphinx Build step does do a similar check, however it only throws warnings and not errors. This additional step can be removed once we integrate numpydoc validation directly with Sphinx by enabling it to throw exceptions instead of warnings. 

This helps with #178

2023-11-13 07:41 UTC, devendragovil commented
I have added the numpydoc-validation as an additional job in the docs workflow to help it isolate from the rest. 

It won't pass for now, as there are a lot of issues in the docstrings that need to be resolved. 

One can get a list of all issues by doing the following:

1. Clone/Pull the repo to sync with upstream.
2. install the new pre-commits.
3. Run the following command: `pre-commit run --all-files numpydoc-validation`
4. To store in a file you can run `pre-commit run --all-files numpydoc-validation &> all_warnings_numpydoc.txt`

I would need everyone's help to resolve #178

2023-11-13 08:02 UTC, ffl096 requested changes
Having looked at this more, I now think using numpydoc validation in a separate step instead of inside Sphinx is a better option indeed. Sphinx has some notorious caching behaviour that swallows warnings on my machine and hinders local validation.

2023-11-13 08:52 UTC, devendragovil commented on toponetx/algorithms/components.py
>          cell(node) components of complex.
Yields is a correction section however numpydoc requires a Returns section, and raises an error without that. I am implementing both the Returns and Yields section for now.

2023-11-13 08:52 UTC, devendragovil commented on .github/workflows/docs.yml
> +          sudo apt-get -y install pandoc
Fixed in new commit.

2023-11-13 08:55 UTC, devendragovil commented on toponetx/algorithms/spectrum.py
>          First k eigevals and eigenvec associated with the hodge laplacian matrix.
Fixed in new commit.

2023-11-13 08:55 UTC, devendragovil commented on toponetx/algorithms/spectrum.py
> +    numpy.ndarray
Fixed in new commit.

2023-11-13 09:03 UTC, devendragovil commented on toponetx/algorithms/components.py
>          cell(node) components of complex.
It doesn't work unfortunately, it raises an error saying that there's both a Returns and Yields section. With only the Yields section, it raises an error saying that there is no Return section found. 

I think I have found the issue, this particular method has no yield keyword, as it is simply returning a generator from a different keyword. I think Returns hence is perhaps more accurate here.

2023-11-13 09:43 UTC, ffl096 commented on toponetx/algorithms/components.py
>          cell(node) components of complex.
I propose to change the method body to
```python3
yield from s_connected_components(domain, s=1, cells=cells, return_singletons=True)
```

This should make validation happy and we can keep the `Yields` section.

2023-11-13 11:12 UTC, devendragovil commented on toponetx/algorithms/components.py
>          cell(node) components of complex.
Done!

2023-11-13 17:54 UTC, devendragovil commented on toponetx/algorithms/components.py
> +    Generator[set[Hashable] | set[tuple[Hashable, ...]], None, None]
Done!

2023-11-14 07:33 UTC, ffl096 approved these changes

2023-11-14 07:33 UTC, merged