small fix to chg addressing empty graph in compute laplacian
pyt-team/TopoNetX pull request #348
Opened 2024-04-04 08:02 UTC by USFCA-MSDS

The code does not handle empty chg.

2024-04-04 10:39 UTC, ffl096 requested changes
Please add a test to catch this error in the future.

2024-04-04 14:58 UTC, USFCA-MSDS commented
> Please add a test to catch this error in the future.

Now the function checks if empty then it returns the zero matrix. Should we change this behavior?

2024-04-04 15:21 UTC, ffl096 commented
That's not what I meant: You want to fix an error. Please write a unit test that failed previously and is fixed now with this change. This prevents regressions in the future :)

2024-04-08 08:30 UTC, ffl096 approved these changes

2024-04-08 08:30 UTC, merged